name: "Drift Scan"
description: "Scan GitHub repositories for configuration drift and compliance issues"
author: "chrismlittle123"

branding:
  icon: "shield"
  color: "blue"

inputs:
  org:
    description: "GitHub organization to scan"
    required: true
  repo:
    description: "Specific repository to scan (optional, scans all if not specified)"
    required: false
  config-repo:
    description: "Name of the config repository (default: drift-config)"
    required: false
    default: "drift-config"
  github-token:
    description: "GitHub token with repo access"
    required: true
  json:
    description: "Output results as JSON"
    required: false
    default: "false"
  fail-on-drift:
    description: "Fail the action if drift is detected"
    required: false
    default: "true"

outputs:
  has-drift:
    description: "Whether drift was detected (true/false)"
    value: ${{ steps.scan.outputs.has-drift }}
  repos-scanned:
    description: "Number of repositories scanned"
    value: ${{ steps.scan.outputs.repos-scanned }}
  repos-with-issues:
    description: "Number of repositories with issues"
    value: ${{ steps.scan.outputs.repos-with-issues }}
  results:
    description: "JSON results (if json input is true)"
    value: ${{ steps.scan.outputs.results }}

runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"

    - name: Install drift
      shell: bash
      run: npm install -g drift-toolkit

    - name: Run drift scan
      id: scan
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        # Pass inputs as environment variables to avoid shell injection
        INPUT_ORG: ${{ inputs.org }}
        INPUT_REPO: ${{ inputs.repo }}
        INPUT_CONFIG_REPO: ${{ inputs.config-repo }}
        INPUT_JSON: ${{ inputs.json }}
        INPUT_FAIL_ON_DRIFT: ${{ inputs.fail-on-drift }}
      run: |
        # Build command using environment variables with proper quoting
        # This prevents shell injection from malicious input values
        ARGS=("scan" "--org" "$INPUT_ORG")

        if [ -n "$INPUT_REPO" ]; then
          ARGS+=("--repo" "$INPUT_REPO")
        fi

        if [ "$INPUT_CONFIG_REPO" != "drift-config" ]; then
          ARGS+=("--config-repo" "$INPUT_CONFIG_REPO")
        fi

        if [ "$INPUT_JSON" = "true" ]; then
          ARGS+=("--json")
        fi

        echo "Running: drift ${ARGS[*]}"

        # Run scan and capture output
        set +e
        if [ "$INPUT_JSON" = "true" ]; then
          OUTPUT=$(drift "${ARGS[@]}" 2>&1)
          EXIT_CODE=$?
          echo "results<<EOF" >> $GITHUB_OUTPUT
          echo "$OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

          # Parse JSON for summary
          if echo "$OUTPUT" | jq -e . >/dev/null 2>&1; then
            REPOS_SCANNED=$(echo "$OUTPUT" | jq -r '.summary.reposScanned // 0')
            REPOS_WITH_ISSUES=$(echo "$OUTPUT" | jq -r '.summary.reposWithIssues // 0')
            echo "repos-scanned=$REPOS_SCANNED" >> $GITHUB_OUTPUT
            echo "repos-with-issues=$REPOS_WITH_ISSUES" >> $GITHUB_OUTPUT
          fi
        else
          drift "${ARGS[@]}"
          EXIT_CODE=$?
        fi
        set -e

        # Set outputs
        if [ $EXIT_CODE -eq 0 ]; then
          echo "has-drift=false" >> $GITHUB_OUTPUT
        else
          echo "has-drift=true" >> $GITHUB_OUTPUT
        fi

        # Handle failure
        if [ $EXIT_CODE -ne 0 ] && [ "$INPUT_FAIL_ON_DRIFT" = "true" ]; then
          echo "::error::Drift detected in $INPUT_ORG"
          exit 1
        fi

        exit 0
