# Example GitHub Actions workflow for drift scanning
# Copy this file to your drift-config repo at .github/workflows/drift-scan.yml

name: Drift Scan

on:
  # Run daily at 9am UTC
  schedule:
    - cron: "0 9 * * *"

  # Run on push to main (when config changes)
  push:
    branches: [main]

  # Allow manual runs
  workflow_dispatch:
    inputs:
      repo:
        description: "Specific repo to scan (leave empty for all)"
        required: false
        type: string

jobs:
  scan:
    name: Scan for drift
    runs-on: ubuntu-latest

    steps:
      - name: Run drift scan
        uses: chrismlittle123/drift-toolkit@main
        with:
          org: ${{ github.repository_owner }}
          repo: ${{ inputs.repo }}
          github-token: ${{ secrets.DRIFT_GITHUB_TOKEN }}
          fail-on-drift: "true"

  # Alternative: Scan and create issue on drift
  scan-with-issue:
    name: Scan and create issue
    runs-on: ubuntu-latest
    if: false # Set to true to use this job instead

    steps:
      - name: Run drift scan
        id: scan
        uses: chrismlittle123/drift-toolkit@main
        with:
          org: ${{ github.repository_owner }}
          github-token: ${{ secrets.DRIFT_GITHUB_TOKEN }}
          json: "true"
          fail-on-drift: "false"

      - name: Create issue on drift
        if: steps.scan.outputs.has-drift == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const title = `Drift detected in ${process.env.REPOS_WITH_ISSUES} repositories`;
            const body = `## Drift Scan Results

            **Organization:** ${{ github.repository_owner }}
            **Repos Scanned:** ${process.env.REPOS_SCANNED}
            **Repos with Issues:** ${process.env.REPOS_WITH_ISSUES}

            Please review and fix the drift issues.

            <details>
            <summary>Full Results (JSON)</summary>

            \`\`\`json
            ${process.env.RESULTS}
            \`\`\`
            </details>
            `;

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body,
              labels: ['drift', 'automated']
            });
        env:
          REPOS_SCANNED: ${{ steps.scan.outputs.repos-scanned }}
          REPOS_WITH_ISSUES: ${{ steps.scan.outputs.repos-with-issues }}
          RESULTS: ${{ steps.scan.outputs.results }}
